/* Automatically generated by './build/bin/build-entry.js' */

import PageHeader from '../packages/page-header/index.js';
import PageContent from '../packages/page-content/index.js';
import PropertyTable from '../packages/property-table/index.js';
import PhotoSwipe from '../packages/photo-swipe/index.js';
import DeleteModal from '../packages/delete-modal/index.js';
import CodeEditor from '../packages/code-editor/index.js';
import RichtextEditor from '../packages/richtext-editor/index.js';
import Button from '../packages/button/index.js';
import Image from '../packages/image/index.js';
import Upload from '../packages/upload/index.js';
import Animate from '../packages/animate/index.js';
import Auth from '../packages/auth/index.js';
import Iframe from '../packages/iframe/index.js';

const components = [
  PageHeader,
  PageContent,
  PropertyTable,
  PhotoSwipe,
  DeleteModal,
  CodeEditor,
  RichtextEditor,
  Button,
  Image,
  Upload,
  Animate,
  Auth,
  Iframe
];

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  // Vue.use(InfiniteScroll);
  // Vue.use(Loading.directive);

  // Vue.prototype.$ELEMENT = {
  //   size: opts.size || '',
  //   zIndex: opts.zIndex || 2000
  // };

  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  // locale: locale.use,
  // i18n: locale.i18n,
  install,
  // CollapseTransition,
  // Loading,
  PageHeader,
  PageContent,
  PropertyTable,
  PhotoSwipe,
  DeleteModal,
  CodeEditor,
  RichtextEditor,
  Button,
  Image,
  Upload,
  Animate,
  Auth,
  Iframe
};
